package py.edu.facitec.mec.view;

import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.JButton;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import py.edu.facitec.mec.controller.CiudadController;
import py.edu.facitec.mec.controller.CiudadControllerImp;
import py.edu.facitec.mec.model.Ciudad;
import py.edu.facitec.mec.util.SoloMayusculas;

public class FormCiudad extends javax.swing.JFrame {

    CiudadController ciudadController;
    
    boolean estadoModificacion;
    
    public FormCiudad(java.awt.Frame parent, boolean modal) {
        
        initComponents();
        
        this.ciudadController = new CiudadControllerImp();
        
        estadoModificacion = false;
        
        estado();
        
        this.setLocationRelativeTo(null);
        
        //Validar solo numeros
        Numeros(tfCodigo);
        
        //Validar solo letras
        Letras(tfNombre);
        Letras(tfIso);
        
        //Validar solo mayusculas
        tfNombre.setDocument(new SoloMayusculas());
        tfIso.setDocument(new SoloMayusculas());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tfCodigo = new javax.swing.JTextField();
        tfNombre = new javax.swing.JTextField();
        tfIso = new javax.swing.JTextField();
        cbEstado = new javax.swing.JCheckBox();
        btnNuevo = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ciudades");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 237, 335, -1));

        jLabel1.setText("Codigo:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 18, -1, -1));

        jLabel2.setText("Nombre:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 47, -1, -1));

        jLabel3.setText("ISO");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 85, -1, -1));

        jLabel8.setText("Estado:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 119, -1, -1));

        tfCodigo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfCodigoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfCodigoFocusLost(evt);
            }
        });
        tfCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfCodigoKeyPressed(evt);
            }
        });
        getContentPane().add(tfCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 110, -1));

        tfNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfNombreFocusGained(evt);
            }
        });
        tfNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfNombreKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfNombreKeyTyped(evt);
            }
        });
        getContentPane().add(tfNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 47, 310, -1));

        tfIso.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfIsoFocusGained(evt);
            }
        });
        tfIso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfIsoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfIsoKeyTyped(evt);
            }
        });
        getContentPane().add(tfIso, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 80, 310, -1));

        cbEstado.setText("Inactivo");
        cbEstado.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                cbEstadoStateChanged(evt);
            }
        });
        cbEstado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cbEstadoKeyPressed(evt);
            }
        });
        getContentPane().add(cbEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 119, -1, -1));

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        btnNuevo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnNuevoKeyPressed(evt);
            }
        });
        getContentPane().add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 77, -1));

        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });
        btnConsultar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnConsultarKeyPressed(evt);
            }
        });
        getContentPane().add(btnConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 75, -1));

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        btnGuardar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnGuardarKeyPressed(evt);
            }
        });
        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 88, -1));

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        btnModificar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnModificarKeyPressed(evt);
            }
        });
        getContentPane().add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 230, 90, -1));

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        btnEliminar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnEliminarKeyPressed(evt);
            }
        });
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, 90, -1));

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        btnCancelar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnCancelarKeyPressed(evt);
            }
        });
        getContentPane().add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 88, -1));

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        btnSalir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnSalirKeyPressed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 310, 90, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfCodigoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfCodigoFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCodigoFocusGained

    private void tfNombreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfNombreFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNombreFocusGained

    private void tfIsoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfIsoFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_tfIsoFocusGained

    private void tfCodigoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfCodigoKeyPressed
        
        if(tfCodigo.getText().isEmpty()){
            
            moverConEnter(evt, btnNuevo);
            
        }else{
            
            moverConEnter(evt, btnConsultar);
            
        }
    }//GEN-LAST:event_tfCodigoKeyPressed

    private void tfNombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfNombreKeyPressed
        moverConEnter(evt, tfIso);
    }//GEN-LAST:event_tfNombreKeyPressed

    private void tfIsoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfIsoKeyPressed
        moverConEnter(evt, cbEstado);
    }//GEN-LAST:event_tfIsoKeyPressed

    private void cbEstadoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbEstadoKeyPressed
        if (estadoModificacion) {
            moverConEnter(evt, btnModificar);
        }else{
            moverConEnter(evt, btnGuardar);
        }
    }//GEN-LAST:event_cbEstadoKeyPressed

    private void btnConsultarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnConsultarKeyPressed
        hacerClicConEnter(evt, btnConsultar);
    }//GEN-LAST:event_btnConsultarKeyPressed

    private void btnGuardarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnGuardarKeyPressed
        hacerClicConEnter(evt, btnGuardar);
    }//GEN-LAST:event_btnGuardarKeyPressed

    private void btnModificarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnModificarKeyPressed
        hacerClicConEnter(evt, btnModificar);
    }//GEN-LAST:event_btnModificarKeyPressed

    private void btnEliminarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnEliminarKeyPressed
        hacerClicConEnter(evt, btnEliminar);
    }//GEN-LAST:event_btnEliminarKeyPressed

    private void btnCancelarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnCancelarKeyPressed
        hacerClicConEnter(evt, btnCancelar);
    }//GEN-LAST:event_btnCancelarKeyPressed

    private void btnSalirKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnSalirKeyPressed
        hacerClicConEnter(evt, btnSalir);
    }//GEN-LAST:event_btnSalirKeyPressed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        if(tfCodigo.getText().isEmpty()){
            FormCiudad consulta = new FormCiudad(this, estadoModificacion);
            consulta.setVisible(true);
        }else{
            estadoModificar();
            consultarClientePorCodito(Integer.parseInt(tfCodigo.getText()));
        }
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        boolean validar = validarCampos();
        if(validar){
            guardar();
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        boolean validar = validarCampos();
        if(validar){
            modificar();
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        eliminar();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        limpiar();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        int opcion = JOptionPane.showConfirmDialog(this, "Desea salir?", "Aviso", 2);
        if (opcion == JOptionPane.YES_OPTION) {
            dispose();
        }else{
            btnSalir.requestFocus();
        }
    }//GEN-LAST:event_btnSalirActionPerformed

    private void cbEstadoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_cbEstadoStateChanged
        if (cbEstado.isSelected()) {
            cbEstado.setLabel("Activo");
        }else{
            cbEstado.setLabel("Inactivo");
        }
    }//GEN-LAST:event_cbEstadoStateChanged

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        estadoInsertar();
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnNuevoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnNuevoKeyPressed
        hacerClicConEnter(evt, btnNuevo);
    }//GEN-LAST:event_btnNuevoKeyPressed

    private void tfNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfNombreKeyTyped
        int limite  = 60;
        if (tfNombre.getText().length()== limite){
            evt.consume();
        }
    }//GEN-LAST:event_tfNombreKeyTyped

    private void tfIsoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfIsoKeyTyped
        int limite  = 3;
        if (tfIso.getText().length()== limite){
            evt.consume();
        }
    }//GEN-LAST:event_tfIsoKeyTyped

    private void tfCodigoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfCodigoFocusLost
        if(tfCodigo.getText().isEmpty()){
            
        }else{
            btnConsultar.doClick();
        }
    }//GEN-LAST:event_tfCodigoFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormCiudad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormCiudad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormCiudad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormCiudad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FormCiudad dialog = new FormCiudad(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    public static javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnSalir;
    private javax.swing.JCheckBox cbEstado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JTextField tfCodigo;
    private javax.swing.JTextField tfIso;
    private javax.swing.JTextField tfNombre;
    // End of variables declaration//GEN-END:variables

private void consultarClientePorCodito(int codigo) {
        
        if (codigo != 0 ) {
            
            Ciudad ciudad = ciudadController.recuperarPorCodigo(codigo);
            
            if (ciudad != null) {
                tfNombre.setText(ciudad.getNombre());
                tfIso.setText(ciudad.getIso());
                if (ciudad.getEstado()) {
                    cbEstado.setSelected(ciudad.getEstado());
                    cbEstado.setLabel("Activo");
                }else{
                    cbEstado.setSelected(ciudad.getEstado());
                    cbEstado.setLabel("Inactivo");
                }
                estadoModificar();
                estadoModificacion = true;
            }else{
                JOptionPane.showMessageDialog(this, "No existe ciudad con este codigo", "Aviso", 1);
                estadoInsertar();
                estadoModificacion = false;
            }
        }else{
            JOptionPane.showMessageDialog(this, "Debes digitar un numero", "Aviso", 2);
        }
    }

    private void guardar() {
        Ciudad ciu = new Ciudad(tfNombre.getText(), tfIso.getText(), cbEstado.isSelected());
        ciudadController.registrar(ciu);
        JOptionPane.showMessageDialog(this, "Nueva ciudad guardada con exito", "Aviso", 2);
        limpiar();
    }

    private void modificar() {
        
        Ciudad ciu = new Ciudad(Integer.parseInt(tfCodigo.getText()), tfNombre.getText(), tfIso.getText(), cbEstado.isSelected());
        
        boolean result = ciudadController.modificar(ciu);
        
        if(result){
            
            JOptionPane.showMessageDialog(this, "Ciudad actualizada con exito", "Aviso", 1);
        }
        
        limpiar();
    }

    private void eliminar() {
        
        int opcion = JOptionPane.showConfirmDialog(this, "Eliminar?", "Aviso", JOptionPane.YES_NO_OPTION);
        
        if (opcion == JOptionPane.YES_OPTION) {
            
            ciudadController.eliminar( Integer.parseInt( tfCodigo.getText() ) );
            
        }
        limpiar();
    }

    private void limpiar() {
        tfCodigo.requestFocus();
        tfCodigo.setText("");
        tfNombre.setText("");
        tfIso.setText("");
        cbEstado.setSelected(false);
        estadoModificacion = false;
        estado();
    }

    private void moverConEnter(java.awt.event.KeyEvent evt, JComponent source) {
        if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
            source.requestFocus();
        }
    }
    
    private void hacerClicConEnter(java.awt.event.KeyEvent evt, JButton buttom){
        if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
            buttom.doClick();
        }
    }
    
    private void estado() {
        tfCodigo.setEnabled(true);
        tfNombre.setEnabled(false);
        tfIso.setEnabled(false);
        btnConsultar.setEnabled(true);
        btnGuardar.setEnabled(false);
        btnModificar.setEnabled(false);
        btnEliminar.setEnabled(false);
        btnCancelar.setEnabled(false);
        btnNuevo.setEnabled(true);
        btnConsultar.setEnabled(true);
        cbEstado.setEnabled(false);
    }

    private void estadoInsertar(){
        tfCodigo.setText("");
        tfCodigo.setEnabled(false);
        tfNombre.requestFocus();
        tfNombre.setEnabled(true);
        tfIso.setEnabled(true);
        btnConsultar.setEnabled(false);
        btnGuardar.setEnabled(true);
        btnModificar.setEnabled(false);
        btnEliminar.setEnabled(false);
        btnCancelar.setEnabled(true);
        btnConsultar.setEnabled(false);
        cbEstado.setEnabled(true);
    }
    
    private void estadoModificar(){
        tfCodigo.setEnabled(false);
        tfNombre.requestFocus();
        tfNombre.setEnabled(true);
        tfIso.setEnabled(true);
        btnConsultar.setEnabled(false);
        btnGuardar.setEnabled(false);
        btnModificar.setEnabled(true);
        btnEliminar.setEnabled(true);
        btnCancelar.setEnabled(true);
        btnNuevo.setEnabled(false);
        cbEstado.setEnabled(true);
    }
    
    private boolean validarCampos(){
        boolean valido = false;
        if(tfNombre.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "El campo Nombres es obligatorio", "Aviso", 1);
            tfNombre.requestFocus();
        }else if(tfIso.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "El campo ISO es obligatorio", "Aviso", 1);
            tfIso.requestFocus();
        }else{
            valido = true;
        }
        return valido;
    }
    
    public final void Letras(JTextField a){
        a.addKeyListener(new KeyAdapter(){
            @Override
            public void keyTyped(KeyEvent e){
                char c = e.getKeyChar();
                if(Character.isDigit(c)){
                    getToolkit().beep();
                    e.consume();
                }
            }
        });
    }
    
    public static final void Numeros(JTextField a){
        a.addKeyListener(new KeyAdapter(){
            @Override
            public void keyTyped(KeyEvent e){
                char c = e.getKeyChar();
                if(Character.isLetter(c)){
//                    getToolkit().beep();
                    e.consume();
                }
            }
        });
    }
}
